services:
  ansible_image:
    image: ansible_host
    build:
      context: .
      dockerfile: ansibleMaster.Dockerfile

  nodes:
    image: nodes
    build:
      context: .
      dockerfile: node.Dockerfile

  # backend:
  #   image: awesome/database
  #   build:
  #     context: backend
  #     dockerfile: ../backend.Dockerfile