
services:
  jenkins:
    image: jenkins:jcasc
    build: ./
    container_name: jenkins-docker
    # privileged: true
    ports:
      - 8080:8080
    # volumes:
    #   - ./jenkins_home:/var/jenkins_home
    #   - /var/run/docker.sock:/var/run/docker.sock
    #   - /usr/local/bin/docker:/usr/local/bin/docker
    environment:
      JENKINS_ADMIN_PASSWORD: password
      JENKINS_ADMIN_ID: admin