version: "3"
services:
  mariadb:
    container_name: mariadb-dev
    image: "mariadb:latest"
    ports:
      - '3306:3306'
    volumes:
      - ./data_dir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
# docker exec -it mariadb-dev bash -c "mysql -u pheonix -ps3cr3t"