version: "3"
services:
  mariadb:
    container_name: mariadb-dev
    image: "mariadb:latest"
    ports:
      - '3306:3306'
    volumes:
      - ./data_dir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sup3rs3cr3t
      MYSQL_DATABASE: pheonix
      MYSQL_USER: pheonix
      MYSQL_PASSWORD: s3cr3t
# docker exec -it mariadb-dev bash -c "mysql -u pheonix -ps3cr3t"