
services:
  mysql:
    image: mysql
    container_name: test-mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  mysql-workbench:
    image: linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/India
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped